name: Release package

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
        required: true
      NODE_CACHE_KEY:
        type: string
        required: true

jobs:
  test:
    name: Release package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Load dependencies from cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          path: node_modules
          key: ${{ inputs.NODE_CACHE_KEY }}

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Run release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISHER_TOKEN }}
